/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    VInput: typeof import('./src/components/VInput.vue')['default']
    VSidebar: typeof import('./src/components/sidebar/VSidebar.vue')['default']
    VSidebarItem: typeof import('./src/components/sidebar/VSidebarItem.vue')['default']
    VSidebarSubItem: typeof import('./src/components/sidebar/VSidebarSubItem.vue')['default']
    VThemeSwitcher: typeof import('./src/components/VThemeSwitcher.vue')['default']
  }
}
