/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleListTaskView: typeof import('./src/components/SingleListTaskView.vue')['default']
    TaskView: typeof import('./src/components/TaskView.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    VCheckAnimated: typeof import('./src/components/icons/VCheckAnimated.vue')['default']
    VCheckbox: typeof import('./src/components/VCheckbox.vue')['default']
    VFlexCol: typeof import('./src/components/layout/VFlexCol.vue')['default']
    VFlexRow: typeof import('./src/components/layout/VFlexRow.vue')['default']
    VGrid: typeof import('./src/components/layout/VGrid.vue')['default']
    VIconCheckAnimated: typeof import('./src/components/icons/VIconCheckAnimated.vue')['default']
    VInput: typeof import('./src/components/VInput.vue')['default']
    VLogo: typeof import('./src/components/VLogo.vue')['default']
    VSidebar: typeof import('./src/components/VSidebar.vue')['default']
    VSidebarItem: typeof import('./src/components/sidebar/VSidebarItem.vue')['default']
    VSidebarSubItem: typeof import('./src/components/sidebar/VSidebarSubItem.vue')['default']
    VTask: typeof import('./src/components/VTask.vue')['default']
    VThemeSwitcher: typeof import('./src/components/VThemeSwitcher.vue')['default']
  }
}
